### ISSUE TITLE
undefined constant _NONE

### ISSUE THREAD

**Issue by cesag** [XoopsModules25x/newbb#10]
When I start the install (modules/system/admin.php?fct=modulesadmin&op=install&module=newbb)

I get these errors:

Notice: Use of undefined constant _NONE - assumed '_NONE' in file /modules/newbb/xoops_version.php line 695
Notice: Use of undefined constant _NONE - assumed '_NONE' in file /modules/newbb/xoops_version.php line 710

module donwloaded from here:
http://github.com/mambax7/newbb

___

My config:

PHP: 5.6.4-4ubuntu6.2 
MYSQL: 5.6.25-0ubuntu0.15.04.1
XOOPS: 2.5.7.1 
ModuleAdmin: 1.2

**Comment by mambax7** [comment]
This should be defined in XOOPS' /language/french/global.php:
define('_NONE','None');
It seems like it is missing there.

**Comment by cesag** [comment]
But Xoops and my modules are in english... :-)

**Comment by mambax7** [comment]
Hmm, can you check if it's in your  /language/english/global.php ?

**Comment by cesag** [comment]
Yes it is present:
define('_NONE','None');

**Comment by mambax7** [comment]
Let me test over here again then...

**Comment by cesag** [comment]
Ok ty, that's a good thing :-)
I will try tomorrow and install a fresh xoops 2.5.7.1 to test again

**Comment by cesag** [comment]
I found where the problem was. When I install rmcommon before installing newbb, I have these two errors:
Notice: Use of undefined constant _NONE - assumed '_NONE' in file /modules/newbb/xoops_version.php line 695
Notice: Use of undefined constant _NONE - assumed '_NONE' in file /modules/newbb/xoops_version.php line 710

If I do not install rmcommon before installing newbb, I do not have those errors
