### ISSUE TITLE
User IP adress on local network

### ISSUE THREAD

**Issue by slider84** [XoopsModules25x/newbb#11]
On a local network, Newbb 4.33 RC10 always report (for any users) 127.255.255.255 as user IP adress (in newbb admin mode).

Xoops 2.5.7.1 - Debian 8.1 - Apache 2.4.10 - MySQL 5.5.44 - Php 5.6.9

**Comment by slider84** [comment]
All IP number > 127 are not store correctly in the database due to bad field attribute in bb_posts table.
The solution: change poster_ip field attribute to UNSIGNED (to allow integer from 0 to 255).

**Comment by mambax7** [comment]
I started conversion of the "poster_ip" field to IPv6 compatible format, i.e. varchar(45). 
https://github.com/mambax7/newbb/commit/b461bd27f7ccd6daf9b3d02db130031b59bb8b44

I've added conversion of existing DB, but we'll need to test it extensively to make sure that it works. Please take a look and see if we can improve it, as this is just a first attempt and I'm sure, there is a room for improvement! :)

**Comment by slider84** [comment]
Ok, i make tests this week ,-)

      De : Mamba (Michael Beck) <notifications@github.com>
 À : XoopsModules25x/newbb <newbb@noreply.github.com> 
Cc : slider84 <slider84d@yahoo.fr> 
 Envoyé le : Dimanche 23 août 2015 6h47
 Objet : Re: [newbb] User IP adress on local network (#11)
   
I started conversion of the "poster_ip" field to IPv6 compatible format, i.e. varchar(45). 
mambax7@b461bd2I've added conversion of existing DB, but we'll need to test it extensively to make sure that it works. Please take a look and see if we can improve it, as this is just a first attempt and I'm sure, there is a room for improvement! :)—

**Comment by mambax7** [comment]
Since I didn't hear any issues on the IPv6 conversion, I assume, I can close it now.
