### ISSUE TITLE
_MD_NEWBB_NEWBB_TYPE undefined

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/newbb#118]
Hi,
I dont find the definition _MD_NEWBB_NEWBB_TYPE in the languages files (english and french language)
It's for the prefix forum type definition like 
[Resolved]
[Bug]
[Info]...
![Capture d’écran 2021-03-11 225429](https://user-images.githubusercontent.com/5336960/110860256-d2fa1780-82bc-11eb-9ede-dc985072ffc3.png)

**Comment by alain01** [comment]
Traduction : May be : "Subject prefix"

**Comment by mambax7** [comment]
It should be _MD_NEWBB_TYPE
I'll submit it to the Core Team

Thanks for the report
