### ISSUE TITLE
Unable to delete user post

### ISSUE THREAD

**Issue by slider84** [XoopsModules25x/newbb#12]
When the forum is moderated, unable to delete a user post.
- In online posts:
ERREUR : No subject selected
Same issue when i want to delete all relatives messages.

- in waiting posts.
No error reported but post still waiting in moderation.

Test with a new installation of Xoops 2.5.7.1 and newbb 4.33Rc10. I used the newbb default forum.

Xoops 2.5.7.1 - Debian 8.1 - Apache 2.4.10 - MySQL 5.5.44 - Php 5.6.9

**Comment by mambax7** [comment]
https://github.com/mambax7/newbb/commit/9555119f803008fa9f403147bdabc80e097b5e9d
