### ISSUE TITLE
Question: Maximum file size

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/newbb#120]
When I send an attachment, it says:
Maximum file size: 500Kb

Where can I change this setting?

**Comment by aquasquale** [comment]
cesagonchu, tu dois faire la modif depuis l'admin en éditant chaque forum indépendamment.

Tu pourras modifier la taille maxi de fichier accepté, et juste au dessous tu peux également sélectionner les extensions autorisées.

Elles doivent bien entendu aussi être autorisées dans mimetype.inc

**Comment by mambax7** [comment]
![image](https://user-images.githubusercontent.com/613686/128788820-bcb1310e-2303-4d6a-ab33-48e7530e4cd6.png)
