### ISSUE TITLE
THEME_FORUM_REPLY already defined

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/newbb#123]
Tested with https://github.com/mambax7/newbb and Xoops 2.5.11 latest version and xswatch4 theme inside.

I get this error when I go to the forum on user side:
`Notice: Constant THEME_FORUM_REPLY already defined in file /themes/xswatch4/language/english/main.php line 44`

I see you added it there:
https://github.com/mambax7/newbb/blob/ec107a568512f0ec406d4ab2699208611541934d/language/english/main.php#L559

___
My config:

Apache/2.4.18 (Ubuntu)
PHP version 7.4.9
MySQLi extension mysqlnd 7.4.9

**Comment by mambax7** [comment]
Yes, it was an issues. I'll submit it to Core as well
