### ISSUE TITLE
functions.forum.php

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/newbb#124]
Tested with https://github.com/mambax7/newbb and Xoops 2.5.11 latest version.

I get this error when I go to the forum on user side at /modules/newbb/viewpost.php?status=new

`Warning: count(): Parameter must be an array or an object that implements Countable in file /modules/newbb/include/functions.forum.php line 67`

___
My config:

Apache/2.4.18 (Ubuntu)
PHP version 7.4.9
MySQLi extension mysqlnd 7.4.9

**Comment by mambax7** [comment]
I couldn't replicate it.

**Comment by cesagonchu** [comment]
I don't see this bug either.
