### ISSUE TITLE
Google plus

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/newbb#125]
You can remove the Google plus icon and its link, it no longer exists.

**Comment by mambax7** [comment]
Where? Can you show a screenshot and/or link where should I look for it?

**Comment by cesagonchu** [comment]
class="col-3 mr-auto d-none d-sm-block"
modules/newbb/templates/images/icon/googleplus.png
![image](https://user-images.githubusercontent.com/4613970/128814135-c16c39a1-0f50-44cb-91e2-ad5d1f0a2824.png)

**Comment by mambax7** [comment]
https://github.com/mambax7/newbb/commit/a2aab2d68c894f1f86f70cb3666d1e166ff905df
