### ISSUE TITLE
THEME_FORUM_REPLY already defined in xswatch4

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/newbb#129]
Latest Core and latest Newbb module, I got this error:

Notice: Constant THEME_FORUM_REPLY already defined in file /themes/xswatch4/language/english/main.php line 44

**Comment by mambax7** [comment]
Already submitted:
https://github.com/XOOPS/XoopsCore25/pull/1278/commits/44707a570caf3d01c2d45a66aa8487218cba9a26#diff-22ecb58213a3f7a862db4aa2f0545216650bec00f4fda65c9286e5a4790b520a
