### ISSUE TITLE
Bug with IPv6

### ISSUE THREAD

**Issue by montuy337513** [XoopsModules25x/newbb#131]
If the user has an IPv6 to connect. It is not possible to post a reply or create a discussion.
The value returned for the IP is too large for the size of the field

```
0,000360 - INSERT INTO bb_posts (topic_id, forum_id, post_time, poster_ip, poster_name, subject, pid, dohtml, dosmiley, doxcode, dobr, uid, icon, attachsig, approved, post_karma, require_reply) VALUES (38347,38,1656533310,2962578927,'','Test de nouveau sujet',0,0,1,1,1,27847,'',1,1,0,0)
Error number: 1264
Error message: Out of range value for column 'poster_ip' at row 1
``` 

The solution found so far is to pass the poster_ip field from int(11) to BIGINT(20).
There may be a more relevant solution to have on how the IP is stored (e.g. storing the IP directly in VARCHAR)

**Comment by mambax7** [comment]
Please use the version 5.x of Newbb. The size of poster_ip is varchar(45):

![image](https://user-images.githubusercontent.com/613686/198815464-9baebf31-51a3-4b1f-b7a4-f697fc72217e.png)
