### ISSUE TITLE
Internal server error in backend admin

### ISSUE THREAD

**Issue by jorgenqv** [XoopsModules25x/newbb#133]
XOOPS Version | XOOPS 2.5.11-Beta2 from Master latest update sept 28, 2022
PHP Version | 8.0.24
MySQL Version | 10.3.36-MariaDB-1:10.3.36+maria~ubu2004
Server API | cgi-fcgi
OS | Linux
fsockopen | On
post_max_size | 256M
max_input_time | 60
output_buffering |
max_execution_time | 300
memory_limit | 2147483648
file_uploads | On
upload_max_filesize | 256M

Default theme

Newbb module version 5.1.0 beta5

When going to Admin for Newbb in backend I get

A problem has occurred on our server!
Page is currently unavailable
We are working on a fix
Please come back soon ...

Error : Error: Call to undefined function exec()

Errors
Error: Error: Call to undefined function exec() in file /modules/newbb/admin/index.php line 74

**Comment by mambax7** [comment]
exec() is a PHP function, so it should be there. 
See: https://www.php.net/manual/en/function.exec.php

Maybe your server is blocking it?

**Comment by jorgenqv** [comment]
Yes it looks like it's disabled.

![phpinfo_20221028](https://user-images.githubusercontent.com/5297223/198531420-1bd5dfca-7444-41d2-9a06-d37997bd7adb.png)

Confirmed it with my host and they cannot permit it. 

It there a way to find another solution to the exec function?

**Comment by mambax7** [comment]
I'm not an expert with ImageMagick, so I don't know how to work with it without the exec() function. 
Some people on the Internet recommend to simply get a VPS instead of the shared server. 

The other option would be to comment out lines:
```php
100 //$imageLibs = newbb_getImageLibs();
135 //$adminObject->addInfoBoxLine(sprintf(_AM_NEWBB_IMAGEMAGICK . ' %s', array_key_exists('imagemagick', $imageLibs) ? _AM_NEWBB_AUTODETECTED . $imageLibs['imagemagick'] : _AM_NEWBB_NOTAVAILABLE));
136 //$adminObject->addInfoBoxLine(sprintf('NetPBM' . ': %s', array_key_exists('netpbm', $imageLibs) ? _AM_NEWBB_AUTODETECTED . $imageLibs['netpbm'] : _AM_NEWBB_NOTAVAILABLE));
137 //$adminObject->addInfoBoxLine(sprintf(_AM_NEWBB_GDLIB . ' %s', array_key_exists('gd', $imageLibs) ? _AM_NEWBB_AUTODETECTED . $imageLibs['gd'] : _AM_NEWBB_NOTAVAILABLE));
```

This will at least allow you to run NewBB.

**Comment by mambax7** [comment]
After commenting out these lines, in Preferences you might select Auto or GD2, and see if that solved the problem, or if it create some new issues:

![image](https://user-images.githubusercontent.com/613686/198549533-783edb25-d955-49c0-85ad-226a146dd3d2.png)

**Comment by jorgenqv** [comment]
Ah yes, it works. Thank you! :)

Looks like my host have GD. Will look further into things...
