### ISSUE TITLE
Overlapping reply box blocking content in default theme

### ISSUE THREAD

**Issue by jorgenqv** [XoopsModules25x/newbb#135]
XOOPS Version | XOOPS 2.5.11-Beta2 from Master latest update sept 28, 2022
PHP Version | 8.0.24
MySQL Version | 10.3.36-MariaDB-1:10.3.36+maria~ubu2004
Server API | cgi-fcgi
OS | Linux
fsockopen | On
post_max_size | 256M
max_input_time | 60
output_buffering |
max_execution_time | 300
memory_limit | 2147483648
file_uploads | On
upload_max_filesize | 256M

Default theme

Newbb module version 5.1.0 beta.6 (mambax7 fork release) and beta-5

The reply function when accessing viewtopic.php seems to be broken when using the default Xoops theme and other older 2.5 compatible themes, but works in xbootstrap and xswatch themes.

The Post reply popup is permanently blocking content. Below the post is a See Quick reply button that works and expands a form that is not working (Submit error Enter a quick reply here).

![Screenshot NewBB 1 72 0 Beta 6 viewtopic 2022-10-28 21-12-47](https://user-images.githubusercontent.com/5297223/198717641-244bf92e-0150-4be4-96ab-9788cf2ddda0.png)

**Comment by mambax7** [comment]
We don't recommend to use the "default" theme - it's not really maintained, and mainly used for testing only. 
Please use the xbootstrap or the xswitch4 theme.

**Comment by jorgenqv** [comment]
Ok thanks. Just tested the xbootstrap and the xswitch4 theme and all reply functions seem to work fine.

**Comment by jorgenqv** [comment]
Just a quick follow-up: The simplest way to solve this is to go into preferences and check No on Enable Quick Reply. So now my really old themes and the old Default works without the blocking box : ) :+1: 
 
![Screenshot Enable Quick reply NO in NewBB preferences 2022-10-30 00-33-59](https://user-images.githubusercontent.com/5297223/198854991-431cd654-b40c-4580-8a92-f9aa742449a4.png)
