### ISSUE TITLE
Added categories forums not shown

### ISSUE THREAD

**Issue by jorgenqv** [XoopsModules25x/newbb#136]
XOOPS Version | XOOPS 2.5.11-Beta2 from Master latest update sept 28, 2022
PHP Version | 8.0.24
MySQL Version | 10.3.36-MariaDB-1:10.3.36+maria~ubu2004
Server API | cgi-fcgi
OS | Linux
fsockopen | On
post_max_size | 256M
max_input_time | 60
output_buffering |
max_execution_time | 300
memory_limit | 2147483648
file_uploads | On
upload_max_filesize | 256M

Default theme

Newbb module version 5.1.0 beta.6 (mambax7 fork release) and beta 5

If you add more Categories and add forums in them, they are not accessable from the index.php front end. The only way is to go from admin backend to reach frontend viewforum.php from the Forum tab.

![screenshot NewBB 1 72 0 Beta 6 no forums in extra categoies 2022-10-28 22-06-34](https://user-images.githubusercontent.com/5297223/198723324-48b5d066-eb68-48f0-a57a-1d9ca8c40d23.png)

**Comment by mambax7** [comment]
We don't recommend to use the "default" theme - it's not really maintained, and mainly used for testing only. 
Please use the xbootstrap or the xswitch4 theme.

**Comment by jorgenqv** [comment]
Yes it's the same issue with xbootstrap, xswitch4 and all other themes I tested. No forums are shown under the categories.

![Screenshot NewBB xbootstrap 2022-10-29 12-43-24](https://user-images.githubusercontent.com/5297223/198827491-fdeb3f62-4efc-4eaa-b4d6-6c1c90b35d20.png)

![Screenshot NewBB xswatch4 2022-10-29 12-52-19](https://user-images.githubusercontent.com/5297223/198827500-a3571d3b-8cb2-408d-9d4e-795d1a9c4ba1.png)

![Screenshot NewBB xswatch 2022-10-29 12-46-46](https://user-images.githubusercontent.com/5297223/198827508-cbc66d39-554b-42ff-9ee2-2aaa6154e133.png)

**Comment by mambax7** [comment]
Click on the Plus icon:

![image](https://user-images.githubusercontent.com/613686/198831944-080ae896-1497-45f2-abdf-cf8fd2fc3edf.png)

**Comment by jorgenqv** [comment]
It's no problem with the Category Test category. 

The issue is that the two categories above have forums but there is no plus icon.

**Comment by mambax7** [comment]
Did you set the permissions correctly to access and to view the forums?

**Comment by jorgenqv** [comment]
Ah yes, this was a bit weird: The permissions look right with the correctly checked boxes. 
Did finally got the forums visible correct by checking on an off a couple of times. 
Thanks!

**Comment by mambax7** [comment]
I'm glad that it is now solved! 
Thanks again for testing and reporting back here!
