### ISSUE TITLE
Unknown: trim() string deprecated

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/newbb#137]
After installing the module, a deprecated message on admin side:
`Unknown: trim(): Passing null to parameter #1 ($string) of type string is deprecated in file /class/libraries/vendor/symfony/yaml/Inline.php line 49`

I know that this should be ignored but I report it.

I think we should fix the deprecated errors, but it's up to you.

___

My config

Newbb 5.1.0 Beta6 from today and here: https://github.com/mambax7/newbb (english version)
Xoops 2.5.11-Beta2 (english version)
PHP 8.1.2
MYSQL 8.0.31-0ubuntu0.22.04.1

**Comment by mambax7** [comment]
This has been reported in XMF:
https://github.com/XOOPS/xmf/issues/96
