### ISSUE TITLE
Mr Wong and Digg links

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/newbb#138]
The link from the forum post to Mr. Wong does not work.
Same for Digg.

___

My config

Newbb 5.1.0 Beta6 from today and here: https://github.com/mambax7/newbb (english version)
Xoops 2.5.11-Beta2 (english version)
PHP 8.1.2
MYSQL 8.0.31-0ubuntu0.22.04.1

**Comment by mambax7** [comment]
done in 5eecc9ab72686ff805adffea639b8e31afa81ff9

Thank you!
