### ISSUE TITLE
Module icon cause internal server error

### ISSUE THREAD

**Issue by slider84** [XoopsModules25x/newbb#14]
Fresh install of xoops 2.5.7.1
In admin mode when you want to install the module, icon not appear and cause internal server error.
![newbb-install-error](https://cloud.githubusercontent.com/assets/11248252/9688840/16c0a602-5332-11e5-9081-801bf7fe3911.png)

**Comment by cesagonchu** [comment]
It seems to be a problem with the .htaccess file.

**Comment by mambax7** [comment]
Is this resolved?

**Comment by cesagonchu** [comment]
No, I asked to montuy337513 (black_beard) to look into it, but I don't know when he has time.

**Comment by mambax7** [comment]
Please keep me posted...

**Comment by cesagonchu** [comment]
montuy337513 (black_beard) will take a look today :-)

**Comment by montuy337513** [comment]
I sent the correction by email

**Comment by mambax7** [comment]
https://github.com/XoopsModules25x/newbb/commit/dc44228d991d7cc862ca0ba531ff6ea784c606ea
