### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/newbb#15]
When I install Newbb and go to modules/profile/userinfo.php?uid=1, I get this error message:
Warning: Invalid argument supplied for foreach() in file /include/notification_functions.php line 353

**Comment by cesagonchu** [comment]
UP!

**Comment by mambax7** [comment]
fixed: https://github.com/mambax7/x258/commit/8e7be42efc3576e13e0fd9ee2af77e5eca2c9746
