### ISSUE TITLE
Can not edit the Topic

### ISSUE THREAD

**Issue by AlexL777** [XoopsModules25x/newbb#16]
Dear developers,

I have a problem with this forum module. I have created the first Forum Topic and it can no longer edit. The system tells me you have to choose, but the frontend in Topic I see nowhere a checkbox or a link. You press "Edit" and is forwarded to the Forum Index.

Is it a bug or am I missing any forum settings. For assistance I would be grateful.
![xoops25-newbb-forum-topic](https://cloud.githubusercontent.com/assets/7885632/9847052/af665144-5ad6-11e5-9352-799ac473d11f.jpg)

**Comment by mambax7** [comment]
Hi Alex,
Unfortunately, there is currently no forum module certified for XOOPS 2.6.0
All modules that you find in this repository here ("XoopsModules25x") are only for XOOPS 2.5.x

The modules that you can test with XOOPS 2.6.0 are included in Alpha release. In the future, we'll place modules certified for XOOPS 2.6.0 in this Repository: https://github.com/XoopsModules26x
