### ISSUE TITLE
Error in toggle_script

### ISSUE THREAD

**Issue by slider84** [XoopsModules25x/newbb#19]
Generate error in page source code.
in footer.php line 45 
$toggle_script = "var toggle_cookie=\"" . $forumCookie['prefix'] . 'G' . '\';';
must be replace by:
$toggle_script = "var toggle_cookie=\"" . $forumCookie['prefix'] . 'G' . '";';

**Comment by mambax7** [comment]
Thanks!  https://github.com/mambax7/newbb/commit/70ffede3679954872ade69232c7af3c555e64f4b
