### ISSUE TITLE
Pagenav in view forum page not working

### ISSUE THREAD

**Issue by slider84** [XoopsModules25x/newbb#20]
Syntax error In viewforum.php line 27
$query_array[$var] = "{$var}={XoopsRequest::getString($var, '', 'GET')}";
must be replace by
$query_array[$var] = "{$var}=".XoopsRequest::getString($var,'','GET');

Thanks to black_beard for the solution.

**Comment by mambax7** [comment]
This was already fixed in my branch on August 9: https://github.com/mambax7/newbb/commit/e4ee03e394263870ccd7a94b4ede6e21622b330e#diff-69fe78dcf1ffebfacb74873c9a308c34
