### ISSUE TITLE
Attachment in Post not working

### ISSUE THREAD

**Issue by myxoops** [XoopsModules25x/newbb#23]
It does not work to attach anything (image or doc) in a forum post.

Here is the debugger output:
Warning: base64_decode() expects parameter 1 to be string, array given in Datei /modules/newbb/post.php Zeile 415
Warning: unlink(/uploads/newbb/): Is a directory in Datei /modules/newbb/post.php Zeile 418
Warning: Illegal offset type in isset or empty in Datei /class/uploader.php Zeile 208

**Comment by mambax7** [comment]
What PHP and XOOPS version?

**Comment by mambax7** [comment]
I did some updates - can you check out and test the latest code?

**Comment by myxoops** [comment]
Thank you!
It works now. Great!
