### ISSUE TITLE
Error line 8 seo.php

### ISSUE THREAD

**Issue by markosc** [XoopsModules25x/newbb#37]
Error line 8 seo.php
:  Can't use function return value in write context in /home/p/public_html/modules/newbb/seo.php on line 8

xoops 2.5.8
master newbb
php 5.6

**Comment by markosc** [comment]
ok, now page blank, " PHP Fatal error:  Class 'XoopsRequest' not found in /home/xxxx/public_html/modules/newbb/seo.php on line 8"

**Comment by mambax7** [comment]
Can you add above the line 8 the following line and test it?
```php
include_once __DIR__ . '/header.php';
```

**Comment by markosc** [comment]
yes, now working 💃

**Comment by markosc** [comment]
working good in the all links but in miweb.com/forum/  (index )It is shown the error 404, modified line 5 of seo_url.php
