### ISSUE TITLE
XoopsObjectTree::$_tree is deprecated

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/newbb#47]
When I go to the module admin permissions (newbb/admin/admin_permissions.php), I get these errors:

Notice: XoopsObjectTree::$_tree is deprecated, accessed from /modules/newbb/class/tree.php line 72, in file /class/tree.php line 307
Notice: XoopsObjectTree::$_tree is deprecated, accessed from /modules/newbb/class/tree.php line 73, in file /class/tree.php line 307
Notice: XoopsObjectTree::$_tree is deprecated, accessed from /modules/newbb/class/tree.php line 64, in file /class/tree.php line 307
___
My config:

PHP: 7.0.13-0ubuntu0.16.10.1
MYSQL: 5.7.17-0ubuntu0.16.10.1
XOOPS: 2.5.9-Beta1 english version

**Comment by mambax7** [comment]
Anything that is "deprecated" can be ignored. The developer will have to make changes in the future, but for now it is working as designed.
