### ISSUE TITLE
Several errors, after creating a category and a forum

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/newbb#48]
Several errors, after creating a category and a forum:

Notice: Undefined property: XoopsMySQLDatabaseProxy::$getServerVersion in file /modules/newbb/class/online.php line 250

Notice: Undefined variable: sub_forums in file /modules/newbb/class/forum.php line 811

Warning: array_keys() expects parameter 1 to be array, null given in file /modules/newbb/class/forum.php line 811

Warning: Invalid argument supplied for foreach() in file /modules/newbb/class/forum.php line 811

And another error when I go to user profile:
Error: Call to a member function getVar() on null in file /modules/newbb/include/functions.user.php line 164

___
My config:

PHP: 7.0.13-0ubuntu0.16.10.1
MYSQL: 5.7.17-0ubuntu0.16.10.1
XOOPS: 2.5.9-Beta1 english version
Newbb from today: 4.33 RC13 english version

**Comment by mambax7** [comment]
Should be fixed now: https://github.com/XoopsModules25x/newbb/releases/tag/v4.33-FINAL
