### ISSUE TITLE
_MD_MESSAGEC already defined

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/newbb#49]
When I go to Newbb admin side, I get this error:

Notice: Constant _MD_MESSAGEC already defined in file /modules/newbb/language/english/main.php line 254

___

My config:
XOOPS Version	XOOPS 2.5.9-Beta1
PHP Version	7.0.13-0ubuntu0.16.10.1
mySQL Version	5.7.17-0ubuntu0.16.10.1

**Comment by mambax7** [comment]
Should be fixed now: https://github.com/XoopsModules25x/newbb/releases/tag/v4.33-FINAL
