### ISSUE TITLE
Undefined offset

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/newbb#50]
When I go to the forum on user side, I get this error:
Notice: Undefined offset: 1 in file /modules/newbb/class/forum.php line 805

___
My config:
XOOPS Version	XOOPS 2.5.9-Beta1
PHP Version	7.0.13-0ubuntu0.16.10.1
mySQL Version	5.7.17-0ubuntu0.16.10.1

**Comment by mambax7** [comment]
Should be fixed now: https://github.com/XoopsModules25x/newbb/releases/tag/v4.33-FINAL
