### ISSUE TITLE
Problem with XoopsPageNav

### ISSUE THREAD

**Issue by chaoos2** [XoopsModules25x/newbb#52]
Unless the topic is show page navigator, that in the particular topic I have a number of items that have a display panel with page numbers, the system reports an error:

**Fatal error: Cannot declare class XoopsPageNav, because the name is already in use in E:\xampp\htdocs\xoops3\class\pagenav.php on line 24**

Problem solved by removing the line 355 in a file viewtopic.php . Thus removing the specific code:
**include $GLOBALS['xoops']->path('class/pagenav.php');**

I got an error somewhere, or it needs to be adjusted?

**Comment by mambax7** [comment]
Hopefully fixed in the 4.33 release:
https://github.com/XoopsModules25x/newbb/releases/tag/v4.33-FINAL
