### ISSUE TITLE
Permissions Errors

### ISSUE THREAD

**Issue by gwydion0917** [XoopsModules25x/newbb#54]
I have recently updated and I am getting permission errors. I can set default permissions and apply them, but I can't manually set permissions. I get "Sorry, you don't have the permission to access this area." and am kicked back to the main website from the admin screens. Is there a fix for this?

**Comment by mambax7** [comment]
Can you try with this version:  https://github.com/XoopsModules25x/newbb/releases/tag/v4.33-FINAL
What XOOPS and PHP version are you using?

**Comment by gwydion0917** [comment]
It was on:

XOOPS Version | XOOPS 2.5.9
PHP Version | 7.1.15
Forum 4.33 Final (11/27/2016)

I will see if I can find time to test it. Because of the error not happening right away, after 4 attempts at setting up my forums with extensive topics, I switched off of xoops.
