### ISSUE TITLE
The Text Editor for messages does not display Bold, Italic, and Xoops code

### ISSUE THREAD

**Issue by ecingala** [XoopsModules25x/newbb#57]
Hi , 

I am using the newBB forum. 
I downloaded the version 4.33 Final 2018-03-24 .
I use Xoops 2.5.9

The text Editor does not take into account the **BOLD** text. All the buttons are impacted in the form.

![image](https://user-images.githubusercontent.com/4630600/45493797-dce44380-b76f-11e8-8e25-25b4b0ec4b78.png)

The error in the console is: 
```
Uncaught ReferenceError: xoopsMakeBold is not defined
    at HTMLButtonElement.onclick (edit.php?topic_id=2&post_id=3:255)
onclick @ edit.php?topic_id=2&post_id=3:255
```

I just need a simple and functionnal text editor.

Thank you very much.

**Comment by ecingala** [comment]
Hi everyone, 

I would like to have an update on this issue, if this is possible.

For more information, the site http://vps555516.ovh.net/xoopstest/modules/newbb/ uses the lastest Xoops Forum (newbb 4.33) on Xoops 2.5.9.  It was installed 2 months ago.

I would like a working forum, which is important for my site. My former site was using newbb : http://vps555516.ovh.net/djsite/modules/newbb/ uses the Xoops Forum module. But it stoped working after a Xoops+php migration.

**What solution do I have to have a working forum?**
What kind of information can I provide to you or any member who want to help?

**Thank you for you support.**
Kind Regards
Eddy

**Comment by mambax7** [comment]
I'll look into it...

**Comment by ecingala** [comment]
Hi Mambax7, 
Thank you very much.
Eddy

**Comment by mambax7** [comment]
What PHP version are you using? 
Was this a fresh installation of XOOPS, or did you upgrade your existing version? If yes, did you run "upgrade", i.e. did you copy the "upgrade" folder to your site, and did you run it via "mysite.com/upgrade"?

I just installed XOOPS 2.5.9 and NewBB 4.3.3 Final, and it works without any problems.

**Comment by ecingala** [comment]
Hi Mambax7, 

This was a fresh installation of Xoops. 

You spot it right: the PHP version is not the one I thought. It is PHP 5.6.36-0+deb8u1 . The provider has kept an old version (I thought it was new because I took the VPS this year). 
I may keep the former Xoops version or upgrade the PHP (and reinstall xoops on new PHP)

Thank you very much
Kind Regards
Eddy
