### ISSUE TITLE
Switch from X-Forum

### ISSUE THREAD

**Issue by walkero-gr** [XoopsModules25x/newbb#68]
I'd like to update our xoops website to newer versions, but X-Forum keeps me back, as it is not compatible, especially with newer versions of PHP, and not maintained any more.

Is there a way to migrate X-Forum content to newBB? is there a guide for that?

**Comment by mambax7** [comment]
You might read this thread on how to do it:
https://xoops.org/modules/newbb/viewtopic.php?post_id=356855#356855

You would need to use the NewBB 4.x for the migration:
https://github.com/XoopsModules25x/newbb/releases/tag/4.34_FINAL

Once this is done and it's working, then you could update to NewBB 5.x:
https://github.com/XoopsModules25x/newbb/releases
