### ISSUE TITLE
Yaml.php

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/newbb#69]
When I install Newbb 5 final with Xoops 2.5.11 Alpha 1, I get this error:

Warning: file_get_contents(/data/xoops_data/configs/newbb_permission_template.php): failed to open stream: No such file or directory in file /class/libraries/vendor/xoops/xmf/src/Yaml.php line 199

https://github.com/XOOPS/XoopsCore25/blob/master/htdocs/class/libraries/vendor/xoops/xmf/src/Yaml.php

line 199: $yamlString = file_get_contents($yamlFile);

Richard answered me here https://xoops.org/modules/newbb/viewtopic.php?post_id=364749#364749 but I think we should fix this.

___

Config
PHP 7.4.2
MYSQL 5.7.29-0ubuntu0.16.04.1
XOOPS 2.5.11-Alpha1

**Comment by mambax7** [comment]
It is still an issue?

**Comment by cesagonchu** [comment]
No.
