### ISSUE TITLE
Errors when deleting forum test

### ISSUE THREAD

**Issue by cesag** [XoopsModules25x/newbb#7]
When I delete the forum test included in the module and go to modules/newbb/admin/admin_forum_manager.php, I get these errors:

Notice: Undefined variable: perms in file /modules/newbb/class/permission.php line 259
Warning: array_keys() expects parameter 1 to be array, null given in file /modules/newbb/class/permission.php line 259
Warning: Invalid argument supplied for foreach() in file /modules/newbb/class/permission.php line 259

______________________________________________
When I go to:
/newbb/admin/admin_permissions.php

I get these errors:

Unknown: Argument 4 passed to newbbXoopsGroupFormCheckBox::_renderOptionTree() must be of the type array, none given, called in /class/xoopsform/grouppermform.php on line 262 and defined in file /modules/newbb/admin/admin_permissions.php line 140
Notice: Undefined variable: parentIds in file /modules/newbb/admin/admin_permissions.php line 144
Warning: Invalid argument supplied for foreach() in file /modules/newbb/admin/admin_permissions.php line 144
Notice: Undefined variable: parentIds in file /modules/newbb/admin/admin_permissions.php line 159
Warning: implode(): Invalid arguments passed in file /modules/newbb/admin/admin_permissions.php line 159

Notice: Undefined variable: perms in file /modules/newbb/class/permission.php line 259
Warning: array_keys() expects parameter 1 to be array, null given in file /modules/newbb/class/permission.php line 259
Warning: Invalid argument supplied for foreach() in file /modules/newbb/class/permission.php line 259
Warning: array_keys() expects parameter 1 to be array, null given in file /modules/newbb/admin/admin_permissions.php line 364
Warning: Invalid argument supplied for foreach() in file /modules/newbb/admin/admin_permissions.php line 364
Notice: Undefined offset: 0 in file /class/xoopsform/grouppermform.php line 255
Warning: Invalid argument supplied for foreach() in file /class/xoopsform/grouppermform.php line 255

_________________________________
My config:

PHP: 5.5.9-1ubuntu4.11
MYSQL: 5.5.43-0ubuntu0.14.04.1
XOOPS: 2.5.7.1

Xoops and the module are in english

**Comment by cesag** [comment]
Are fixes planned?

**Comment by mambax7** [comment]
Of course!!! :)

**Comment by cesag** [comment]
Ok ty :-D

**Comment by mambax7** [comment]
You can you run a short test on code from https://github.com/mambax7/newbb

**Comment by cesag** [comment]
Ok ty ;-)
On install, I get 2 errors:
Warning: Missing argument 5 for ArtObjectHandler::__construct(), called in /modules/newbb/class/text.php on line 42 and defined in file /Frameworks/art/object.php line 71
Notice: Undefined variable: identifierName in file /Frameworks/art/object.php line 74

**Comment by mambax7** [comment]
Thanks Cesag for testing. You can ignore the errors related to ArtObject - they will be fixed in XOOPS 2.5.8
Any other issues that you've discovered?

**Comment by cesag** [comment]
I did not go further. I will test with XOOPS 2.5.8

2015-08-01 13:48 GMT+02:00 Mamba (Michael Beck) <notifications@github.com>:

**Comment by mambax7** [comment]
You mean, you were NOT able to install it?

**Comment by cesag** [comment]
Yes, I was able to install it, but I did not continue to do tests.
Same error messages, at installation with XOOPS 2.5.8.
Xoops 2.5.8 downloaded from here:
http://sourceforge.net/p/xoops/svn/HEAD/tree/XoopsCore/branches/2.5.x/2.5.8/htdocs/

**Comment by mambax7** [comment]
"will be fixed in XOOPS 2.5.8" :)
Please keep reporting any other issues you might find...

**Comment by cesag** [comment]
Errors reported at the beginning of this discussion seem to have been fixed.
It remains to resolve those related to ArtObject.
Yes, I've found other issue :-) I will open a new thread.
