### ISSUE TITLE
NEWBB_NOTOPIC define

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/newbb#70]
In \newbb\EXTRA\themes\xbootstrap\modules\newbb\newbb_index.tpl
line 221
replace
<{$smarty.const._AM_NEWBB_NOTOPIC}>
with
<{$smarty.const._MD_NEWBB_NOTOPIC}>

**Comment by geekwright** [comment]
_Sorry for the bad tag. Once you mess it up, there doesn't seem to be a way to fix it._ :(
