### ISSUE TITLE
_MD_NEWBB_AUTO_CREATE_ABOUT

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/newbb#73]
According to **JJDai** here:
https://www.frxoops.org/modules/newbb/viewtopic.php?post_id=241500#forumpost241500

the define **_MD_NEWBB_AUTO_CREATE_ABOUT** is empty in newbb/language/english/main.php line 546.
It is called in newbb/include/functions.welcome.inc.php line 67

I think the define could be like this:
define('_MD_NEWBB_AUTO_CREATE_ABOUT', 'About');

**Comment by mambax7** [comment]
I guess, it was done to save space
