### ISSUE TITLE
NEWBB_ADMIN_DEFINED and include once command

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/newbb#74]
JJDai's suggestion:
This code:
```
if (defined('NEWBB_ADMIN_DEFINED')) {
     return;
}
define('NEWBB_ADMIN_DEFINED', true);
```

> is useless since Xoops loads files with the "include_once" command which guarantees that the file is loaded only once. In addition, the constants in question are unused from what I see.`

**Comment by mambax7** [comment]
I commented it out
