### ISSUE TITLE
_GDLIBVERSION

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/newbb#75]
According to JJDai:

This code:

`define('_CO_NEWBB_GDLIBVERSION', 'GD Library version: ');`

is better than:

`define('CO_' . $moduleDirNameUpper . '_GDLIBVERSION', 'GD Library version: ');`

in newbb/language/english/common.php line 24

> The concatenation is recalculated for each constant, it seems useless to me or it would have to be done in all the language files, but that does not seem to me a good idea.

> Better to declare these constants as in the other files.

> In addition, the constants should be prefixed with a "_" as in other language files, to remain consistent.

> It requires making this change throughout the code.`

**Comment by mambax7** [comment]
The file "common.php" is a generic file for all modules, i.e. we can just copy it to any module, and it will work there, e.g. 
```php
$html .= '<li>' . \constant('CO_' . $moduleDirNameUpper . '_GDLIBVERSION') . '<b>' . $gdlib['GD Version'] . '</b>';
```
