### ISSUE TITLE
Error when wanted to print

### ISSUE THREAD

**Issue by cesag** [XoopsModules25x/newbb#8]
When I want to print a message (modules/newbb/print.php?form=2&forum=2&topic_id=2&post_id=2), I get this error:
ERROR: Topic not selected!

I think it's due to my url. My xoops is installed on a subdomain like this:

xxx.mydomain.com

**Comment by mambax7** [comment]
https://github.com/mambax7/newbb/commit/3a020a1b2f484b9614fba29e7f2d2c4eeccc9f6b
