### ISSUE TITLE
Permissions errors

### ISSUE THREAD

**Issue by cesag** [XoopsModules25x/newbb#9]
When I install newbb and go to newbb/admin/admin_permissions.php, I get these errors:

Unknown: Argument 4 passed to newbbXoopsGroupFormCheckBox::_renderOptionTree() must be of the type array, none given, called in /class/xoopsform/grouppermform.php on line 262 and defined in file /modules/newbb/admin/admin_permissions.php line 140
Notice: Undefined variable: parentIds in file /modules/newbb/admin/admin_permissions.php line 144
Warning: Invalid argument supplied for foreach() in file /modules/newbb/admin/admin_permissions.php line 144
Notice: Undefined variable: parentIds in file /modules/newbb/admin/admin_permissions.php line 159
Warning: implode(): Invalid arguments passed in file /modules/newbb/admin/admin_permissions.php line 159
___
My config:

PHP: 5.6.4-4ubuntu6.2 
MYSQL: 5.6.25-0ubuntu0.15.04.1
XOOPS: 2.5.7.1 
ModuleAdmin: 1.2

**Comment by mambax7** [comment]
Seems to be working OK here: https://github.com/mambax7/newbb
