### ISSUE TITLE
Quick Reply template

### ISSUE THREAD

**Issue by walkero-gr** [XoopsModules25x/newbb#96]
Hello guys,
Is it possible to change the look of Quick Reply form at the end of a topic page? I had a look at the module template folder and didn't find a tpl file for this block.

In ViewTopic tpl file the quick reply form is included at the following line only.
`<div><{$quickreply.form}></div>`

How could someone do that?
Thank you for your help.

**Comment by mambax7** [comment]
It looks like it is set in viewtopic.php starting on line 812 through 832. 
It probably would make sense to extract it into a template, so give it a try...

**Comment by mambax7** [comment]
Did you get a chance to do it?

**Comment by walkero-gr** [comment]
@mambax7 
Actually, sorry, but I didn't work on that at all. Priorities changed to be honest. I will close this ticket.
